Home work02
RevskyAndrey/MOK20-21 pull request #3
Opened 2020-11-11 06:05 UTC by RevskyAndrey

2020-11-12 00:04 UTC, XX-NF-XX commented on src/.env
> +ORIGIN=http://localhost:3000
Обычно `.env` файлы ложат в корень проекта, в `src` только код

2020-11-12 00:12 UTC, XX-NF-XX commented on src/app.js
> +// boot(goods, 'type', 'socks');
Закомментированного кода в `git` не должно быть.
Комментарий должен нести полезную информацию, иначе он только мешает.

2020-11-12 00:21 UTC, XX-NF-XX reviewed
Всё хорошо. Двигаешься в правильном направлении.

2020-11-12 07:03 UTC, RevskyAndrey commented on src/.env
> +ORIGIN=http://localhost:3000
преместил

2020-11-14 21:09 UTC, XX-NF-XX requested changes
Требуются небольши изменения, но в целом всё хорошо!

2020-11-14 21:09 UTC, XX-NF-XX commented on src/controllers/controller.js
> +}
`home` и `comment` не обязательны в этой домашке. Они были просто для примера.

2020-11-14 21:09 UTC, XX-NF-XX commented on src/controllers/controller.js
> +}
Необыное название для функции которая записывает список продуктов в JSON файл.

2020-11-15 08:46 UTC, RevskyAndrey commented on src/utils/requestHandler.js
> +    const queryParams = parseQuery(parsedUrl.search.substr(1));
Спасибо за информацию и детальное описание

2020-11-15 08:49 UTC, RevskyAndrey commented on src/controllers/controller.js
> +}
comment использовал для пост запроса

2020-11-15 16:40 UTC, XX-NF-XX approved these changes
Отлично!
Один небольшой момент:
Логично бы было обновить `goods` в `controller.js` после того как загрузился новый файл. Сейчас получается так, что новые данные загружены, но сервер продолжает отдавать результат по старым данным.

2020-11-15 16:40 UTC, merged