Home work03
RevskyAndrey/MOK20-21 pull request #4
Opened 2020-11-15 19:58 UTC by RevskyAndrey

2020-11-17 01:09 UTC, XX-NF-XX requested changes
Согласно заданию №2 функция по генерации скидки должна выполняться с задержкой в 50 мсек, а в коде задержек нет.

2020-11-17 01:09 UTC, XX-NF-XX commented on src/task/discount.js
> +    data = err.message;
По заданию должна возвращаться ошибка а не строка

2020-11-26 20:24 UTC, RevskyAndrey commented on src/task/discount.js
> +  }
принял к сведению

2020-11-26 20:25 UTC, RevskyAndrey commented on src/task/discount.js
> +  const max = Math.floor(99);
взято было из урока )

2020-11-27 06:22 UTC, XX-NF-XX requested changes
Отлично.
Логика построена правильно, а эндпоинт отдаёт правильный результат.
Но необходимы небольшие исправления:
- `myMap` никак не задействован, его нужно где-то применить.
- необходимо включить ESlint (https://www.jetbrains.com/help/webstorm/eslint.html) и внести изменения:
  - задействовать `ESlint` в `task3` и обновить код.
  - исправить все ошибки `ESlint`:

```
/src/controllers/controller.js
  45:1   error  Delete `⏎`              prettier/prettier
  48:1   error  Delete `··`             prettier/prettier
  49:55  error  Delete `⏎`              prettier/prettier
  54:32  error  Delete `⏎·······`       prettier/prettier
  60:1   error  Delete `⏎`              prettier/prettier
  64:1   error  Replace `⏎}⏎` with `}`  prettier/prettier

/src/task/discount.js
   4:7   error  'myMap' is assigned a value but never used  no-unused-vars
   5:7   error  'task3' is assigned a value but never used  no-unused-vars
  11:1   error  Delete `⏎`                                  prettier/prettier
  34:41  error  Delete `⏎`                                  prettier/prettier

/src/task/index.js
  7:1  error  Replace `⏎module.exports·=·{·task1,·task2,·task3,·myMap,·discount` with `module.exports·=·{·task1,·task2,·task3,·myMap,·discount·`  prettier/prettier

✖ 11 problems (11 errors, 0 warnings)
```

2020-11-27 06:22 UTC, XX-NF-XX commented on src/task/task3.js
> +    return { type, color, quantity, price, isPair, discount };
`ESlint` в данном случае вполне обоснованно возмущается.
Необходимо убрать все комментарии отключающие `ESlint` и обновить код.

2020-11-27 17:23 UTC, XX-NF-XX approved these changes
Отлично! 👍

2020-11-27 17:23 UTC, merged