Home work04
RevskyAndrey/MOK20-21 pull request #7
Opened 2020-12-01 20:59 UTC by RevskyAndrey

2020-12-02 14:04 UTC, XX-NF-XX commented on src/server/routes/routes.js
> +  }
Чтобы попасть в этот роут нужно передать хеадер. Логичнее было бы поместить его в обычные роуты, т.к. этот роут стримами не занимается.

2020-12-02 14:17 UTC, XX-NF-XX requested changes
Есть мелкий баг, а в остальном всё отлично. Даже учтено что может прийти маленький чанк.
Круто! 👍 
Осталось оптимизацию и готово.

2020-12-02 14:17 UTC, XX-NF-XX commented on src/server/routes/routes.js
> +}
После создания файла и ответа клиенту выполнение переходит в `notFound(response);` который пытается записать в закрытый стрим и приложение выключается.

2020-12-02 19:56 UTC, RevskyAndrey commented on src/server/routes/routes.js
> +  }
был баг в постмене ) решил спустил в handleRoutes

2020-12-06 16:40 UTC, XX-NF-XX approved these changes
Огонь! Всё работает правильно с первого раза! Есть один ньюанс, но его легко исправить. 🥇 
Круто!

2020-12-06 16:40 UTC, XX-NF-XX commented on src/server/utils/csvToJson.js
> +module.exports = csvToJson();
Поскольку функция вызывается только один раз при загрузке модуля, то она создаёт один объект стрима, который, отработав один раз больше работать не будет, т.к. он уже закрыт.
Поэтому тут лучше экспортировать не результат вызова функции, и назвать функцию например `createCsvToJson`. Таким образом в контроллере эта фунция будет вызываться каждый раз и каждый раз она будет создавать новый стрим на каждый новый запрос.
В данный момент конвертация работает только первый раз, потом создаёт пустые файлы.  При этом каждый следующий запрос не закрывается.

2020-12-06 16:48 UTC, RevskyAndrey commented on src/server/utils/csvToJson.js
> +module.exports = csvToJson();
пофиксил

2020-12-06 17:00 UTC, merged